name: Bump version
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm install
      - name: Build Source Code
        run: npm run build
      - name: Run Unit Tests
        run: npm run test

  version:
    needs: test
    name: Create Git Tag Version & Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: "https://npm.pkg.github.com"
      - name: Create NPM Version
        run: npm version $(node -e "console.log('$(git describe --tags)'.split('-')[0])") --no-git-tag-version
      - name: Install Dependencies
        run: npm install
      - name: Build Source Code
        run: npm run build
      - name: Attach Registry
        run: echo "@zackheil:registry=https://npm.pkg.github.com" > .npmrc
      - name: Publish Package Version
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
